<!doctype html>
<html lang="jp">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>プロジェクト進捗状況14</title>
    
    <link rel="stylesheet" href="project3のコピー.css">
</head>
<body>
    <!--h1は見出し１（大見出し）-->
　<h1>プロジェクト進捗状況15　（2022.03.20）</h1>
<br>
<h2>◉Fusion360で足元ヒータースタンドの製作</h2>
<br>
<br>
　　　介護用品と直接関係はないが、足先が冷えやすいので足元ヒーターを使用している。<br>
　　　コンパクトサイズで地面に直接置いて使用するタイプなので、足先ではなく足首に直接温風が来てしまうことを避けるために、今回は角度調節スタンドを作成する。<br>
<br>
<br>
<br>
<br>
<img src="スクリーンショット 2022-03-24 14.18.40.png" alt=""><br>
　　「上部」<br>
　　　スケッチより、上底70mm・下底100mmの台型を描き、ロフトで高さ10mmの土台を作る。<br>
<br>
<br>
<br>
<img src="スクリーンショット 2022-03-24 14.18.59.png" alt=""><br>
　　　フィレットで角を丸くする。<br>
<br>
<br>
<br>
<img src="スクリーンショット 2022-03-24 14.19.56.png" alt=""><br>
　　「下部」<br>
　　スケッチより、上底50mm・下底130mmの台型を描き、ロフトで高さ25mmの土台を作る。<br>
<br>
<br>
<br>
<br>
<img src="スクリーンショット 2022-03-24 14.20.16.png" alt=""><br>
　　　上部と同様にフィレットで角を丸くする。<br>
<br>
<br>
<br>
<br>
<img src="スクリーンショット 2022-03-24 14.22.32.png" alt=""><br>
　 　ボルトを軸として角度調整を可能とするために接合パーツを作成する。<br>
　 　スケッチで20mm×20mmの正方形を書き、10mm押し出しを行い立体にする。<br>
　 　10mmのボルトが入るようにスケッチで直径12mmの円を描き押し出しで切り抜く。<br>
　　 　※（印刷ノズルの関係でスムーズに入るように多少大きく設計した。）<br>
<br>
<br>
<br>
<br>
<img src="スクリーンショット 2022-03-24 14.24.41.png" alt=""><br>
　 　接合パーツを複製し、上部・下部に接合する。<br>
<br>
<br>
<br>
<br>
<img src="スクリーンショット 2022-03-24 14.28.12.png" alt=""><br>
　 ・軸となるボルトとナットの作成。<br>
　 　スケッチで直径10mmの円を描き、70mm押し出しで立体後ネジを切る。<br>
<br>
　 ・ナットの作成<br>
　　 ポリゴンで五角形を描き、１０mm押し出す。直径12mmの円で内部をくり抜く。<br>
　　 くり抜いた穴にネジ切る。<br>
<br>
<br>
<br>
<br>
<h3>　◉使用例</h3>
<img src="スクリーンショット 2022-04-01 18.24.22.jpeg" alt=""><br>
　　　本体との接合は３Mの両面テープを使用した。<br>
　　　使用感としては、好みの角度に調節できるため以前よりも使用しやすくなった。<br>
<br>
　　　※ボルトが対荷重に耐えられず、折れてしまったためステンレスボルトで代用した。<br>
　　　
<br>
　
　　
　　
    <footer>

    </footer>
